spring.datasource.jdbc-url=${DB_URL}
spring.datasource.username=${DB_ID}
spring.datasource.password=${DB_PASSWORD}

logging.level.web=INFO

#logging.file.path=/home/ubuntu/logs/
logging.file.path=/logs/
logging.file.name=apartment.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.file-name-pattern=${logging.file.name}-%d{yyyy-MM-dd}-%i.log

scheduling.job.cron=0 0 22 * * *

spring.admin.userid=${ADMIN_USERID}
spring.admin.userpw=${ADMIN_USERPW}

# API 설정
api.geocoder.url=https://api.vworld.kr/req/address
api.geocoder.service-key=${GEOCODER_SERVICE_KEY}

api.apt.url=http://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev
api.apt.service-key=${APT_SERVICE_KEY}

jwt.service.key=${JWT_SERVICE_KEY}